services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro

  app:
    build:
      context: ..                # ВАЖНО: корень проекта
      dockerfile: deploy/Dockerfile
    env_file:
      - ./.env                   # потому что .env рядом с compose
    environment:
      HOST: 0.0.0.0
      PORT: "8080"
      APP_HTTPS: "0"
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    # ...
    ports:
      - "8080:8080"
    volumes:
      - ../uploads:/app/uploads  # чтобы файлы сохранялись снаружи

volumes:
  db_data:
